### ISSUE TITLE
Mismatch between README and example programs

### ISSUE THREAD

**Issue by williamjshipman** [CNugteren/CLTune#34]
README.md states that `./sample_conv X Y` will run the convolution sample on device `X` of platform `Y`. However, the sample actually hard codes the platform (platform 0 always). I'm working on updated code in a separate fork and am happy to submit a PR when its finished.

**Comment by williamjshipman** [comment]
I see that `sample_simple` hard codes both the platform and device IDs. Is that intentional?

**Comment by CNugteren** [comment]
You are right about `sample_simple`, but the other two samples do accept the device/platform argument. The `sample_simple` was left 'simple' intentionally, but you are right that it doesn't match the README.

**Comment by CNugteren** [comment]
Thanks for the pull-request, it is merged into the dev branch.

**Comment by williamjshipman** [comment]
Glad to be of assistance.
