### ISSUE TITLE
GEMM on input sizes that are not a power of 2

### ISSUE THREAD

**Issue by ari-wwu** [CNugteren/CLTune#47]
Hello together,

performing GEMM on input sizes that are not a power of 2 (e.g., matrices of the size 2000x2000) leads to errors:

```
[==========] Initializing on platform 0 device 0
[==========] Device name: 'Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz' (OpenCL 1.2 AMD-APP (1912.5))

[----------] Testing reference gemm_reference
[ RUN      ] Running gemm_reference
[       OK ] Completed gemm_reference (10915.9 ms) - 1 out of 1

[----------] Testing kernel gemm_fast
[ RUN      ] Running gemm_fast
[   FAILED ] Kernel gemm_fast failed
[   FAILED ]   catched exception: Internal OpenCL error: -54
[  WARNING ] Results differ: L2 norm is 1.90e+08
[   FAILED ] gemm_fast;      0.0 ms;  MWG 128;  NWG 128;   KWG 32; MDIMC 32;  NDIMC 8; MDIMA 32; NDIMB 16;    KWI 8;    VWM 1;    VWN 1;   STRM 1;   STRN 0;     SA 1;     SB 1;PRECISION 32;
[ RUN      ] Running gemm_fast
[   FAILED ] Kernel gemm_fast failed
[   FAILED ]   catched exception: Internal OpenCL error: -54
[  WARNING ] Results differ: L2 norm is 1.90e+08
[   FAILED ] gemm_fast;      0.0 ms;  MWG 128;   NWG 64;   KWG 32; MDIMC 32; NDIMC 16; MDIMA 32; NDIMB 16;    KWI 8;    VWM 1;    VWN 4;   STRM 1;   STRN 0;     SA 1;     SB 1;PRECISION 32;
[ RUN      ] Running gemm_fast
[   FAILED ] Kernel gemm_fast failed
[   FAILED ]   catched exception: Internal OpenCL error: -54
[  WARNING ] Results differ: L2 norm is 1.90e+08
[   FAILED ] gemm_fast;      0.0 ms;  MWG 128;   NWG 64;   KWG 32; MDIMC 32; NDIMC 16; MDIMA 32; NDIMB 32;    KWI 8;    VWM 1;    VWN 2;   STRM 1;   STRN 0;     SA 0;     SB 1;PRECISION 32;
```

Does someone now how to fix it (without using approaches such as padding etc.)?

**Comment by CNugteren** [comment]
I assume you are referring to the GEMM example included as part of the CLTune repository? It indeed does make some assumptions, perhaps they should be documented better.

But it's just an example of how to use the tuner. If you want a fully functional GEMM kernel, you can look at e.g. [CLBlast](https://github.com/CNugteren/CLBlast). What is your goal you would like to accomplish?

**Comment by ari-wwu** [comment]
Yes, I am referring to the GEMM example included as part of the CLTune repository.

I am currently also working on an auto-tuning tool and want to compare my results with those of the CLTune library.

Without having analyzed the GEMM Kernel, I can imagine that when generalizing the tuning parameters' definitions to

  tuner.AddParameter(id, "MWG", { 1, ..., kSizeM } );  // here, "{ 1, ..., kSizeM }" is a pseudo code notation for the set of integers from 1 to kSizeM
  tuner.AddParameter(id, "NWG", { 1, ..., kSizeN } );
  tuner.AddParameter(id, "KWG", { 1, ..., kSizeK } );
  tuner.AddParameter(id, "MDIMC", { 1, ..., kSizeM } );
  tuner.AddParameter(id, "NDIMC", { 1, ..., kSizeN } );
  tuner.AddParameter(id, "MDIMA", { 1, ..., kSizeM } );
  tuner.AddParameter(id, "NDIMB", { 1, ..., kSizeN } );
  tuner.AddParameter(id, "KWI", { 1, ..., kSizeK } );
  tuner.AddParameter(id, "VWM", { 1, ..., kSizeM } );
  tuner.AddParameter(id, "VWN", { 1, ..., kSizeN } );
  tuner.AddParameter(id, "STRM", {0, 1});
  tuner.AddParameter(id, "STRN", {0, 1});
  tuner.AddParameter(id, "SA", {0, 1});
  tuner.AddParameter(id, "SB", {0, 1});
  
  
the GEMM kernel can be tuned for arbitrary-sized input matrices -- is that correct? If not, can you help to adapt the tuning parameters' definitions to reach the goal (probably also by using a pseudo code notation as above)? That would be great.

**Comment by CNugteren** [comment]
No, that's not going to work. The included sample is a kernel that has some restrictions on the matrix sizes. If I recall correctly, it is that `m` has to be a multiple of `MWG`, `n` a multiple of `NWG` and `k` a multiple of `KWG`. Perhaps there are other constraints as well.

For more details on GEMM kernels you could take a look at:
* https://cnugteren.github.io/tutorial/pages/page1.html (and subsequent pages)
* Performance Tuning of Matrix Multiplication in OpenCL on Different GPUs and CPUs. K. Matsumoto, N. Nakasato, S.G. Sedukhin. In: SC-Companion '12. IEEE.

If you want to benchmark a GEMM kernel, I would refer to [CLBlast](https://github.com/CNugteren/CLBlast), which contains an un-constraint GEMM kernel and also support tuning through CLTune.
