### ISSUE TITLE
Using CLTune for optimizing saxpy

### ISSUE THREAD

**Issue by ari-wwu** [CNugteren/CLTune#48]
I try to use CLTune for tuning an OpenCL saxpy implementation. The kernel is as follows:

```
__kernel void saxpy( const          size_t   N,
                     const          float    a,
                     const __global float*   x,
                           __global float*   y
                   )
{
  for( int w = 0; w < WPT; ++w ) {
    const int id = w * get_global_size(0)
                     + get_global_id(0);

    y[ id ] += a * x[ id ];
  }
}
```

It is an simplified version of the [CLBLast saxpy]( https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level1/xaxpy.opencl) kernel where the usage of OpenCL vector data types is removed and the input data type is set to `float`.
For this kernel, we have the following tuning-parameters: i) the work per thread (`WPT`), and ii) the local size (`LS`).

My suggestion for a corresponding CLTune program is as follows:

```
// CLTune program for tuning saxpy
int main()
{
  // Set kernel and input size
  const auto   saxpy = /* path to kernel */
  const size_t N       = /* input size     */

  // Declare input data
  float a;
  auto  vec_x = std::vector<float>( N );
  auto  vec_y = std::vector<float>( N );

  // Initialize random number generator
  const auto random_seed = std::chrono::system_clock::now().time_since_epoch().count();
  std::default_random_engine generator(static_cast<unsigned int>(random_seed));
  std::uniform_real_distribution<float> distribution(-2.0f, 2.0f);

  // Fill input data
  a = distribution(generator);
  for (auto &item: vec_x) { item = distribution(generator); }
  for (auto &item: vec_y) { item = distribution(generator); }

  // Initializes the tuner (platform 1, device 0)
  cltune::Tuner tuner( 1, 0 );
  tuner.UseAnnealing( 1.0f / 2048.0f, 4.0 );
  auto id = tuner.AddKernel( saxpy, "saxpy", { N }, { 1 } );
  
  // Set tuning-parameters
  tuner.AddParameter(id, "LS", {1, ... , N} );
  tuner.AddParameter(id, "WPT", {1, ... ,N} );

  // Sets constraints on parameters
  auto DividesN       = []( std::vector<size_t> v ){ return  N % v[0]         == 0; };
  auto DividesNDivWPT = []( std::vector<size_t> v ){ return (N / v[0]) % v[1] == 0; };
 
  tuner.AddConstraint(id, DividesN      , {"WPT"}        );
  tuner.AddConstraint(id, DividesNDivWPT, {"WPT", "LS"} );

  // Modifies the thread-sizes (both global and local) based on the parameters
  tuner.MulLocalSize(id, {"LS"} );
  tuner.DivGlobalSize(id, {"WPT" } );

  // Sets the function's arguments.
  tuner.AddArgumentScalar( N );
  tuner.AddArgumentScalar( a );
  tuner.AddArgumentInput(vec_x);
  tuner.AddArgumentOutput(vec_y);

  // Starts the tuner
  tuner.Tune();
  tuner.PrintToFile("output.csv");
}
```

Here, I have some difficulties: 
1) Does CLTune provide a convenient way to define large tuning-parameter ranges. Here, in my suggested CLTune program above, I use a pseudo-code notation of the form `1,...,N` to represent the range of `size_t` values from `1` to `N`.

2) Can the best found configuration that CLTune finally determines be accessed within the C++ code or do I have to read it out of the file `output.csv`?

3) Can someone confirm that the CLTune program above is correct and in a form that the CLTune developer would approve for tuning the saxpy kernel?

Many thanks in advance.

**Comment by CNugteren** [comment]
1. I was going to answer that `tuner.AddParameter` takes an `std::vector<size_t>` as input, but apparently it doesn't. I just changed it in the `development` branch from `std::initializer_list` to `std::vector`. The old case should still work, but now you can also construct a list first and then pass it on (e.g.   `auto values = std::vector<size_t>(); for (size_t i = 1; i < 64; ++i) { values(i); }`).

2. It outputs either to screen or to file. I guess it makes a lot of sense to also be able to return the best configuration values back to the user. I'll work on that.

3. Yes, I think that's a perfectly valid approach. I just managed to compile and run your code (with some adjustments of course - it doesn't compile out of the box). I didn't test it in detail though. One problem I had was with the `tuner.UseAnnealing` option. I had to disable it to make it work, but I can try to find out later what's going on, perhaps the parameters are just not suitable for the settings I tested with?

**Comment by ari-wwu** [comment]
Many thanks! Regarding your last question: maybe increasing `N` helps?

**Comment by CNugteren** [comment]
I just pushed to the `development` branch. It should fix every issue you pointed out:

1. The new `tuner.AddParameter` API now accepts an `std::vector` (see my previous comment).

2. I added a new `tuner.GetBestResult()` function to the API to retrieve the parameters. It returns an `std::unordered_map<std::string, size_t>`. You can now do something like this:
```
  tuner.PrintToScreen();
  const auto parameters = tuner.GetBestResult();
  printf("\nBest parameter values:\n");
  for (const auto & parameter : parameters) {
    printf("%s => %zu\n", parameter.first.c_str(), parameter.second);
  }
```

3. There was indeed a bug in the simulated annealing related to 0 neighbours as you pointed out. It is fixed now.

**Comment by ari-wwu** [comment]
Many thanks for your help! I updated the code as follows:

```
int main()
{
  const std::string saxpy = /* path to saxpy kernel    */;
  const size_t      N     = /* an arbitrary input size */;
  
  cltune::Tuner tuner(1,0);
  auto id = tuner.AddKernel(saxpy, "saxpy", {N}, {1} );
  
  float a;
  auto  x = std::vector<float>(N);
  auto  y = std::vector<float>(N);

  const auto random_seed = std::chrono::system_clock::now().time_since_epoch().count();
  std::default_random_engine generator( static_cast<unsigned int>(random_seed) );
  std::uniform_real_distribution<float> distribution(-2.0f,2.0f);

  a = distribution(generator);
  for (auto &item: x) { item = distribution(generator); }
  for (auto &item: y) { item = distribution(generator); }

  tuner.AddArgumentScalar( N );
  tuner.AddArgumentScalar( a );
  tuner.AddArgumentInput( x );
  tuner.AddArgumentOutput( y );

  auto range = std::vector<size_t>( N );
  for( size_t i = 0; i < N ; ++i )
    range[ i ] = i;
  tuner.AddParameter( id, "LS" , range );
  tuner.AddParameter( id, "WPT", range );

  auto DividesN = []( std::vector<size_t> v )
                  {
                    return  N % v[0] == 0;
                  };
  auto DividesNDivWPT = []( std::vector<size_t> v )
                        {
                          return ( N / v[0] ) % v[1] == 0;
                        };
 
  tuner.AddConstraint( id, DividesN      , {"WPT"}       );
  tuner.AddConstraint( id, DividesNDivWPT, {"WPT", "LS"} );

  tuner.DivGlobalSize(id, {"WPT" } );
  tuner.MulLocalSize(id, {"LS"} );
  
  tuner.UseAnnealing( 1.0f/2048.0f , 4.0 );
  tuner.Tune();
  const auto parameters = tuner.GetBestResult();
}
```

Do you think this is the most optimal variant for tuning the saxpy kernel above with CLTune, and is the program equivalent to the CLTune program that CLBlast uses for tuning saxpy (when ignoring tuning the OpenCL vector data type).

Many thanks for your help and best wishes.

**Comment by CNugteren** [comment]
Depends on how you define 'most optimal' :-)

But I think it is perfectly valid what you do. You can [check here](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xaxpy.cpp) what CLBlast does, it only explores these parameters:
```
    tuner.AddParameter(id, "WGS", {64, 128, 256, 512, 1024, 2048});  // work-group size
    tuner.AddParameter(id, "WPT", {1, 2, 4, 8});  // work-per-thread
    tuner.AddParameter(id, "VW", {1, 2, 4, 8});  // vector-width
```

**Comment by ari-wwu** [comment]
Do you have any reason for exploring only a subset of the search space in CLBlast? For example, the restricted search space  seems to not allow performing saxpy on input vectors x and y of a size < 64 or a size that is not a power of 2, is that right?

**Comment by CNugteren** [comment]
> Do you have any reason for exploring only a subset of the search space in CLBlast?

One reason is that it should remain practical and the tuning time shouldn't be too long. The other reason is that for most cases these tuning parameters will be among the best performing ones. For example, non-power of 2 or super small work-group sizes don't make too much sense typically.

> For example, the restricted search space seems to not allow performing saxpy on input vectors x and y of a size < 64 or a size that is not a power of 2, is that right?

The tuner in CLBlast tunes the [fast-version of the axpy-kernel](https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level1/xaxpy.opencl#L44), so indeed it has some restrictions.

**Comment by ari-wwu** [comment]
Thank you very much for all the help!
