### ISSUE TITLE
compiling with Clover (Mesa OpenCL) sample_conv gives errors

### ISSUE THREAD

**Issue by MigMuc** [CNugteren/CLTune#49]
I am currently trying to build CLTune with Mesa OpenCL on AMD Tonga platform.
The sample_conv_simple runs out of the box but sample_conv gives errors:
```
Device compiler error/warning: <unknown>:0:0: in function conv void (i32, i32, float addrspace(1)*, float addrspace(2)*, float addrspace(1)*): unsupported call to function LoadLocalPlusHalo
[   FAILED ] Kernel conv failed
```

When the keyword `inline` is removed from *.opencl files the code compiles.
I also noticed that it runs only if I run the sample_conv_simple prior to the latter program.
```
./sample_conv
[==========] Initializing on platform 0 device 0
[==========] Device name: 'AMD TONGA (DRM 3.8.0 / 4.9.11-1-ARCH, LLVM 3.9.1)' (OpenCL 1.1 Mesa 17.0.0)
[----------] Testing reference conv_reference
[ RUN      ] Running conv_reference
[       OK ] Completed conv_reference (65.7 ms) - 1 out of 1
[----------] Testing kernel conv
[ RUN      ] Running conv
[       OK ] Completed conv (86.1 ms) - 1 out of 22
[ RUN      ] Running conv
[       OK ] Completed conv (91.9 ms) - 2 out of 22
[ RUN      ] Running conv
[       OK ] Completed conv (67.3 ms) - 3 out of 22
```

**Comment by CNugteren** [comment]
This construct is used in many other libraries, so this could be an issue with Clover/Mesa. Examples are [CLBlast](https://github.com/CNugteren/CLBlast/search?l=OpenCL&q=inline&utf8=%E2%9C%93) and [ArrayFire](https://github.com/arrayfire/arrayfire/search?l=OpenCL&q=inline&utf8=%E2%9C%93). I guess you are also unable to run those?

From my understanding most compilers will inline all functions anyway, but apparently the NVIDIA compiler will not always do it unless the user specifies the `inline` keyword. However, I can't find any official Khronos reference to the `inline` keyword, so I'm not sure whether this a bug in Clover/Mesa or just something that almost all compilers support but is not part of the standard... Not sure what to do at this point.

Why it would work the second time is a big mystery, perhaps there is some caching going on in Clover/Mesa? Or perhaps a bug in the OpenCL implementation?

**Comment by MigMuc** [comment]
Clover/Mesa works with llvm/clang. I found an interesting site:

[http://clang.llvm.org/compatibility.html#inline](url)

I have not been able to run CLBlast nor clBLAS tests without any errors. I think the OpenCL
implementation from Mesa seems not to be mature enough to run these libraries (I haven't testet ArrayFire yet).

**Comment by MigMuc** [comment]
I could run all the examples (with inline key word removed) without any errors after I upgraded my Clover/Mesa/LLVM setup
``` Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 17.0.4
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD TONGA (DRM 3.9.0 / 4.10.10-1-ARCH, LLVM 4.0.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 17.0.4
  Driver Version                                  17.0.4
  Device OpenCL C Version                         OpenCL C 1.1
``
