### ISSUE TITLE
setting global size

### ISSUE THREAD

**Issue by ari-wwu** [CNugteren/CLTune#50]
I try to use CLTune for tuning the `XgemmDirect` kernel which is part of the [CLBlast](https://github.com/CNugteren/CLBlast/tree/master/src/kernels/level3) library.
In CLBlast,  the global size is set as `((1 + ((kSizeM - 1) / WGD))*WGD * MDIMCD) / WGD` in dimension 1 and as `((1 + ((kSizeN - 1) / WGD))*WGD * NDIMCD) / WGD` in dimension 2. Is it possible to set the same global in CLTune?

**Comment by CNugteren** [comment]
Somehow I missed this issue, sorry for the late reply. Not sure what you mean though? CLBlast uses CLTune for tuning, so yes, everything that is done in CLBlast is possible in general with CLTune.
