### ISSUE TITLE
[ERROR] Entries for a single kernel with multiple argument values

### ISSUE THREAD

**Issue by kindloaf** [CNugteren/CLTune#51]
Hi, I used the CLTuner to tune some GPU.
After running the tuners and downloading the json files from the device, I ran the script scripts/database/database.  Then I saw the following error:
```
...
[database] Saving database to './scripts/database/database.json'
[database] Calculating the best results per device/kernel...
[database] Calculating the default values...
[ERROR] Entries for a single kernel with multiple argument values: ARM;GPU;32;xgemm;Xgemm
```
Any advice?

**Comment by kindloaf** [comment]
Looking into the python script further, I checked the variable `group` that caused the issue.
It seems that there were 2 entries in the `group` variable. What can cause this to happen?
When I ran the tuners, I ran all the tuners in the build folder (clblast_tuner_*).

**Comment by CNugteren** [comment]
This is an issue with [CLBlast](https://github.com/CNugteren/CLBlast) and not with CLTune itself.

The error message you are seeing indicates that the script found results for the `ARM;GPU;32;xgemm;Xgemm` configuration with multiple arguments (e.g. different matrix sizes). The database script is really ment for production, and thus it assumes that all tuners were run with the same (default) arguments. This message normally occurs when you want to add tuning results with non-default sizes, but the database script doesn't know what to do with that. However, I think that in this case you might actually be using the default settings and that the CLBlast database for SGEMM on ARM was generated using non-default (smaller) matrix sizes to reduce tuning time.

As an alternative for testing you could manually edit the parameters in e.g. https://github.com/CNugteren/CLBlast/blob/master/src/database/kernels/xgemm_direct.hpp or perhaps remove the old entries from the database by hand (it is a human-readable JSON file). Or for now not add any GEMM results for ARM. Or perhaps re-run the tuner for GEMM with the arguments as are currently in the database (I just checked: `-n 512 -m 512 -k 512`). 

I'll work on clarifying the error message and perhaps adding an override to choose either the existing or the newly added argument values.

**Comment by kindloaf** [comment]
@CNugteren Thanks for the explanation in details.
I have a related question - there are 4 files that contain "xgemm" in the tuning result:
clblast_xgemm_1_32.json
clblast_xgemm_2_32.json
clblast_xgemm_direct_1_32.json
clblast_xgemm_direct_2_32.json
What are the difference between "1" and "2", and between "non-direct" and "direct"?

**Comment by kindloaf** [comment]
By the way, I ended up hacking the tuning result (.json files) a bit - I changed the arg_m / arg_n / arg_k from 1024 to 512, pretending it's tuned with a smaller size. And the database.py succeeded without errors.

**Comment by CNugteren** [comment]
> By the way, I ended up hacking the tuning result (.json files) a bit - I changed the arg_m / arg_n / arg_k from 1024 to 512, pretending it's tuned with a smaller size. And the database.py succeeded without errors.

Although that makes it 'work', it is not a nice solution: those manually changed results are now considered to have been for 512x512 matrices, whereas their timing results (in seconds) are corresponding to 1024x1024 matrices.

I have now updated the database script in CLBlast. This is now in the `development` branch. Here is an example of me trying to add results for AXPY with a non-default setting for `n` (4096 instead of 4194304):
```
[database] Processing './clblast_xaxpy_32.json' with 44 new items
[database] WARNING: entries for a single kernel with multiple argument values (u'AMD', u'GPU', u'32', u'xaxpy', u'XaxpyFast')
[database] Either quit now, or remove all but one of the argument combinations below:
[database]     0: (u'4096', u'2.00')
[database]     1: (u'4194304', u'2.000000')
[database] Remove entries corresponding to (u'4096', u'2.00'), [y/n]? y
[database] Removed 1 entry/entries
[database] Remove entries corresponding to (u'4194304', u'2.000000'), [y/n]? n
[database] Saving database to '../scripts/database/database.json'
```
