### ISSUE TITLE
Not complied on embdded GPU

### ISSUE THREAD

**Issue by ghost** [CNugteren/CLTune#52]
Hello

Using CLTune and running "sample_gemm"  there are errors 
```

[----------] Testing kernel gemm_fast
device compiler error/warning: (277:0) : error : require any typed expression except arrays, structures containing arrays, sampler types, and structures containing sampler types
(293:0) : error : require any typed expression except arrays, structures containing arrays, sampler types, and structures containing sampler types
(321:0) : error : require a matching typed expression
(388:0) : error : require a struct/union or vector typed expression
(389:0) : error : require a struct/union or vector typed expression
(494:0) : error : function: 'LocalToPrivateA' hasn't the corresponding declaration
(502:0) : error : function: 'LocalToPrivateB' hasn't the corresponding declaration
(509:0) : error : function: 'MultiplyAccumulate' hasn't the corresponding declaration
(520:0) : error : function: 'StoreResults' hasn't the corresponding declaration

[   FAILED ] Kernel gemm_fast failed
[   FAILED ]   catched exception: device compiler error/warning occurred ^^

[   FAILED ] gemm_fast;      0.0 ms;   MWG 32;  NWG 128;   KWG 32; MDIMC 16; NDIMC 16; MDIMA 16; NDIMB 32;    KWI 2;    VWM 2;    VWN 2;   STRM 0;   STRN 0;     SA 1;     SB 1;PRECISION 32;

```

can you indicate what might be a rootcuase of it?

Thank you.

**Comment by CNugteren** [comment]
What device are you on? Apparently something in the kernel that is not compatible with your OpenCL device. I suggest commenting out bits of the kernel and seeing which parts cause it, if the error messages are too cryptic.

**Comment by peter73421** [comment]
I am to trying to run on NXP i.MX device with Vivatne GPU - clamaied as
OpenCL 1.2 FP device.

**Comment by CNugteren** [comment]
Ah, the Vivante compiler is indeed quite limited. I'm afraid you'll have to modify the example kernel if you want to play around with it. One known limitation is that it doesn't accept arrays as arguments in functions, see [e.g. here for an example of making another kernel compatible with Vivante](https://github.com/CNugteren/CLBlast/commit/1cbe2ea301c6b28a7d1101142ff347471f7dc197). You'll have to do something similar if you want to have that example working. If you want a tuned GEMM, then I suggest you look at [CLBlast instead](https://github.com/CNugteren/CLBlast).
