### ISSUE TITLE
crash on my mac

### ISSUE THREAD

**Issue by xiebaiyuan** [CNugteren/CLTune#54]
./sample_conv_simple 

[==========] Initializing on platform 0 device 0
[   INFO   ] Device vendor: 'Apple'
[   INFO   ] Device name: 'Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz'
[   INFO   ] Device extra info: ''
[   INFO   ] Platform version: 'OpenCL 1.2 (Oct 29 2018 21:43:16)'

[----------] Testing kernel conv
[ VERBOSE  ] Computing the permutations of all parameters
[1]    78238 segmentation fault  ./sample_conv_simple

**Comment by CNugteren** [comment]
Apple's OpenCL implementation is know to be very quirky with workgroup size restrictions, so that seems to be the most likely issue. Try setting the local size to 1, 1 for example.

**Comment by xiebaiyuan** [comment]
ok  thanks~
