### ISSUE TITLE
half.h

### ISSUE THREAD

**Issue by saniv** [CNugteren/CLTune#55]
Hi! Your half-float conversion is broken, because it maps larger numbers (>65536.0) to infinity. So you can't really do any HDR with them.

**Comment by CNugteren** [comment]
I'm no expert on that matter. I took the fp16 conversion functions from http://half.sourceforge.net, which is supposed to implement the IEEE standard. If you think it is incorrect, please point to the part that is incorrect specifically and the documentation of the standard. Perhaps you can check with http://half.sourceforge.net as well?

**Comment by saniv** [comment]
Sorry. I've checked it, and fp16 isn't IEEE standard, so it behaves differently from usual float and double. It is optimized solely for [-1.0; 1.0] range, so expects values to be normalized. Although theoretically, a hacked version of it can represent values up to 131072, which can be useful when fp16 is used as index into a lookup table, like i.e. for pow(x,1/2.2), which I'm using it for.

**Comment by CNugteren** [comment]
Yes it behaves differently, but it is an IEEE standard I guess (https://en.wikipedia.org/wiki/Half-precision_floating-point_format). Anyway, doesn't matter, this is what it is :-)

**Comment by saniv** [comment]
Yeah. They actually standardized it. I remember it being just some NVidia internal thingie. There is also bfloat16 format, which indeed acts as a normal float.
